### ISSUE TITLE
Support landscape mode

### ISSUE THREAD

**Issue by hoodi** [trufi-association/trufi-app#271]
If you use the app in landscape mode the text fields at the top take a lot of space.
It would be nice if they would automatically be arranged next to each other, similar to Google Maps.

**Comment by christophhanser** [comment]
Is it now possible to see a little bit more when we move the screen
horicontally?

**Comment by mdoelker** [comment]
Are you asking if I actually implemented this feature request like it was described? I did.

**Comment by christophhanser** [comment]
Yes, was a stupid question of me.

I only remembered that we wanted to have more space in landscape Mode.

Will have to read more carefully what has been written here and might open
another Ticket.

Lg Christoph

**Comment by mdoelker** [comment]
I'm just messing with you :) But your question has a point in that the available space is still not optimal yet. The text in the lower instruction panel can also a rearranged in collapsed mode to make more space.
