### ISSUE TITLE
Menu shouldn't scroll vertically

### ISSUE THREAD

**Issue by hoodi** [trufi-association/trufi-app#290]
In the menu you can scroll the menu vertically even though there is enough space to show all menu elements.
Probably the header size with the title should be reduced so that all menu items fit without scrolling.

**Comment by mdoelker** [comment]
Does that mean that menu items are not visible due to the header being to big? What is your screen size?

**Comment by mdoelker** [comment]
This is now also a style element, so the header should remain its size even if that makes the menu scroll earlier. Closing.
