### ISSUE TITLE
Mention that app is Open Source in about section

### ISSUE THREAD

**Issue by mdoelker** [trufi-association/trufi-app#304]
We should promote that the app is fully open source inside the app where we talk about our team and the association :) First open source public transport app for iOS, woohoo!

**Comment by amenk** [comment]
Some text like this:

"This app is released as open source on [GitHub](https://github.com/trufi-association/trufi-app/). Feel free to contribute or bring it to your own city."

And maybe include the GPL v3 Logo:

https://de.wikipedia.org/wiki/Datei:GPLv3_Logo.svg

**Comment by amenk** [comment]
Also Trufi's own License should be included as top-most entry behind the Licenses button ...

**Comment by christophhanser** [comment]
True!

**Comment by mdoelker** [comment]
@amenk The license page is using a pre-made widget from the material package that fetches licenses from the `LicenseRegistry` and automatically groups and orders them. We can show a notice on the main about page though.

**Comment by amenk** [comment]
Let's leave the license widget as it is. This can be closed now, I think?

**Comment by mdoelker** [comment]
Yep
