### ISSUE TITLE
Error when running the app

### ISSUE THREAD

**Issue by rmstaanaIT** [trufi-association/trufi-app#313]
> Launching lib\main.dart on ANE LX2J in debug mode...
> Initializing gradle...
> Resolving dependencies...
> * Error running Gradle:
> ProcessException: Process "C:\Users\STAANA\Github\trufi-app\android\gradlew.bat" exited abnormally:
> Starting a Gradle Daemon (subsequent builds will be faster)
> 
> Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterEvaluate {} error.
> 
> FAILURE: Build failed with an exception.
> 
> * Where:
> Build file 'C:\Users\STAANA\Github\trufi-app\android\app\build.gradle' line: 20
> 
> * What went wrong:
> A problem occurred evaluating project ':app'.
> > C:\Users\STAANA\Github\trufi-app\android\key.properties (The system cannot find the file specified)
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 46s
>   Command: C:\Users\STAANA\Github\trufi-app\android\gradlew.bat app:properties
> 
> Finished with error: Please review your Gradle project setup in the android/ folder.
>

**Comment by mdoelker** [comment]
C:\Users\STAANA\Github\trufi-app\android\key.properties (The system cannot find the file specified)

You need to place this file for a release build. If you just want to compile a debug build for testing, you can comment out the *release* subsection in *signingConfigs* and *buildTypes* sections in build.gradle.

**Comment by amenk** [comment]
Shouldn't there be a specific build flavor "debug" to make it easier for those who did not / do not want to create a release signing key?

**Comment by amenk** [comment]
@mdoelker Not ad-hoc, but I saw this at OsmAnd. maybe with flutter there can be a centralized properties / settings file for both Android and iOS? Maybe @kolaente has an idea :)

**Comment by kolaente** [comment]
@amk @mdoelker afaik you'd need to add seperate flavours to https://github.com/trufi-association/trufi-app/blob/develop/android/app/build.gradle#L22

**Comment by amenk** [comment]
Did not really work, because the key.properties file is evaluated too early ...

will probably do it like this:

https://stackoverflow.com/a/38046932/288568

or is this too over engineered?

**Comment by kolaente** [comment]
@amenk Does it work with a blank flutter project?

**Comment by amenk** [comment]
I don't know .. I tried it in this project, but it leads to strange build errors. We might as well just update the documentation and point out, that a key.properties is needed.

**Comment by rmstaanaIT** [comment]
Thank you! I built the app with key.properties. It was successful (no errors) but the app is stuck on the first splash screen. Did I miss something?

**Comment by mdoelker** [comment]
Do you get any error output on the console?

**Comment by rmstaanaIT** [comment]
1. Installed
2.  Cloned
3. Copied the configuration file: `$ cp assets/cfg/app_config.json.dist assets/cfg/app_config.json`
4. Added my settings, private Map Tiler key and OTP server in the configuration file.
5. Filled the `android/key.properties` with path and password.

Error when adding starting point and destination: Failed to load plan

> Exception caught by widgets library
> The following NoSuchMethodError was thrown building Builder:
> 
> The getter 'iterator' was called on null. Receiver: null Tried calling: iterator
> 
> User-created ancestor of the error-causing widget was: 
> MaterialApp file:///C:/Users/MYPC/trufi-app/lib/main.dart:133:16
> 
> When the exception was thrown, this was the stack: 
> #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
> #1      new List.from (dart:core-patch/array_patch.dart:52:19)
> #2      ChooseLocationPageState.initState (package:trufi_app/pages/choose_location.dart:31:24)
> #3      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4068:58)
> #4      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3919:5)

**Comment by amenk** [comment]
Seems like a problem with the OTP server. Can you share it's URL?

**Comment by amenk** [comment]
Which branch are you on? Can you try develop maybe it's https://github.com/trufi-association/trufi-app/issues/315

**Comment by rmstaanaIT** [comment]
> Seems like a problem with the OTP server. Can you share it's URL?

manila-otp.trufi.app

**Comment by amenk** [comment]
okay, https://manila-otp.trufi.app/ is even return trip data for 01.01.2018 -- so that is not the problem what I thought about.

I tried with
   "urlOtpEndpoint": "https://manila-otp.trufi.app/otp/routers/default",
and it basically seems to work.

What is your latest commit? Did you make any non-commited code changes (other than the config JSON) ?

You could also try to use the Android Studio debugger.

**Comment by mdoelker** [comment]
The endpoint was broken earlier. I messaged Christian to fix it.

**Comment by rmstaanaIT** [comment]
I only made changes on the config and added offline tiles. 

I tried `https://manila-otp.trufi.app/ `and `https://manila-otp.trufi.app/otp/routers/default`, sometimes it works then it would show "Failed to load plan" after another run

**Comment by mdoelker** [comment]
Resolved by #326
