### ISSUE TITLE
Add Amharic translation

### ISSUE THREAD

**Issue by amenk** [trufi-association/trufi-app#318]
We want to add Amharic translations.

As I can see there are different translation files, some auto generated. Which files do we edit?

**Comment by christophhanser** [comment]
You can add a file here:
https://github.com/trufi-association/trufi-app/tree/develop/translations

Malte has set up a formular, but since you are a developer... ;)

/Christoph

**Comment by mdoelker** [comment]
You can upload the arb files to Google Translate Toolkit for translating. When done, download the translated arb file and put it into the folder. Then run `generate_translations.sh` to generate the dart classes.

This will have to change in the near future though, as Google Translate Toolkit was just deprecated and will be taken offline soon.

**Comment by mdoelker** [comment]
Does that solve it for you? Also keep track of #330 as we have to migrate away from Google Translate Toolkit now.

**Comment by amenk** [comment]
I guess we will do it manually ... it's not that hard ... it's a JSON file in the end :)

We already started: https://github.com/AddisMap/yeneguzo-app/blob/master/translations/trufiapp_am_ET.arb

**Comment by mdoelker** [comment]
https://www.npmjs.com/package/arb-convert Here is another choice

**Comment by amenk** [comment]
Added manually and via lokalize, no we just have to complete it.
