### ISSUE TITLE
Documentation: How is search.json generated for other cities

### ISSUE THREAD

**Issue by amenk** [trufi-association/trufi-app#320]
Looks like https://github.com/trufi-association/trufi-app/blob/develop/assets/data/search.json is used to power the search drop down in offline mode.

How is that file generated?

I looked at https://github.com/trufi-association/osm-public-transport-export and it might be of help, but the output there is stops.json / routes.json, but no POIs... and not own combined file.

**Comment by mdoelker** [comment]
I'm currently preparing the lib to generate search data for publishing. Will probably finish it this weekend.

**Comment by mdoelker** [comment]
@amenk https://github.com/trufi-association/osm-search-data-export and use the json-compact output
