### ISSUE TITLE
Introduce a "Share this app" button

### ISSUE THREAD

**Issue by christophhanser** [trufi-association/trufi-app#321]

**Comment by christophhanser** [comment]
![image](https://user-images.githubusercontent.com/10851343/66107458-a10d5d80-e5c0-11e9-9fed-059317e1fcd0.png)

Add a simple button "Share this App", so that the user can choose with which APP she wants to distribute the following information: "Ya conoces a la Trufi App? Descargua lo aqui <URL>"

The URL is different for Playstore and App Store.

**Comment by amenk** [comment]
Also it might make sense to share the APK for sideloading, if the app grows bigger, to save download data...

**Comment by christophhanser** [comment]
What is sideloading?

With Share the App I rather mean to easily invite others to install and use
the App.

/Christoph

**Comment by amenk** [comment]
I know what you mean.

I wanted to add that it might be interesting to share the APK itself to an other device. It's quite common in Ethiopia. Via apps like xender.

**Comment by christophhanser** [comment]
This Flutter package looks promising: https://pub.dev/packages/share

**Comment by mdoelker** [comment]
APK sharing is out of scope for this issue but something to look at

**Comment by christophhanser** [comment]
@alexander, Feel free to open a new Ticket.

/Christoph
