### ISSUE TITLE
Moving the map shows blank tiles

### ISSUE THREAD

**Issue by rmstaanaIT** [trufi-association/trufi-app#327]
![](https://media.giphy.com/media/idN2Vkb67e9XAiOPRu/giphy.gif)

**Comment by christophhanser** [comment]
That happens with Bad Internet Connection, when the maptiles cannot be
loaded from maptiler. Could that be the case?

**Comment by mdoelker** [comment]
That is normal behaviour and not a bug. We currently use rasterized tiles. So each tile has to be loaded independently and there are different zoom levels that have their own set of tiles.

That said we are trying to figure out a way to switch to vector tiles which will potentially easen that issue dramatically.

**Comment by RaimundWege** [comment]
Also a new version of the `flutter_map` package will use scaled tiles from other layers (if any exist) until new tiles are available. The issue is tracked [here](https://github.com/johnpryan/flutter_map/issues/79).
