### ISSUE TITLE
Workflow: How should we handle new translations?

### ISSUE THREAD

**Issue by amenk** [trufi-association/trufi-app#328]
See https://github.com/trufi-association/trufi-app/pull/322#issuecomment-539196394

There are also new translations like followOnTwitter

On a non English phone, the local language (German in my case) is preselected and I cannot test the develop branch any more.

What is the workflow for new translations? Is it okay, if develop runs only on en_US and other languages will be added later? Or shall we add English strings (better than red-screens) for the languages the developer who introduces a new string, does not know?

**Comment by mdoelker** [comment]
We should have English as a fallback language in case a string is missing, as the English translation should always be there (if the developer did not forget to generate the files). I was somehow assuming this is already the case. I’ll have a look how that can be done.

**Comment by mdoelker** [comment]
Closing as the red screen issue is resolved. But of course, we should have most if not all translations ready before a release.

**Comment by amenk** [comment]
How was it resolved? I only added DE.. other languages night still be broken.

Or were they added / or the fallback implement?

**Comment by mdoelker** [comment]
I edited my earlier comment, maybe that was not visible enough. Yes, it now shows the original English version in that case.

**Comment by amenk** [comment]
Nixe, thanks for clarifying
