### ISSUE TITLE
[dev] App based on generalize code branch - has different version for the compile (1.0.0) and runtime (1.1.0) classpath

### ISSUE THREAD

**Issue by amenk** [trufi-association/trufi-app#354]
I am am getting this error when building our derived app:

	* What went wrong:                                                      
	Execution failed for task ':app:preDebugBuild'.                         
	> Android dependency 'androidx.versionedparcelable:versionedparcelable' has different version for the compile (1.0.0) and runtime (1.1.0) classpath. You should manually set the same version via DependencyResolution
		             

Did you see this before?

Good brings me to https://github.com/flutter/flutter/issues/27254 

I tried this solution https://github.com/flutter/flutter/issues/27254#issuecomment-468526704 which leads me to also upgrade kotline which does seem to be a bit too much change.

@RaimundWege

**Comment by amenk** [comment]
Found also this one .. maybe it's really a bug in flutter?

https://github.com/AmolGangadhare/flutter_barcode_scanner/issues/60

**Comment by amenk** [comment]
Seems to happen also when building the example/ app

**Comment by mdoelker** [comment]
On which commit is this based? I recently updated dependencies for the newest Flutter SDK, but it is not fully tested. You might want to test this on an earlier commit.

**Comment by amenk** [comment]
One the latest branch commit ..

**Comment by mdoelker** [comment]
Might be related to a change in Flutter SDK then. You might go back then for the moment.

**Comment by amenk** [comment]
I tried revert 

    git revert 8e78917f65b1cac9d9f01c844f3d1a292ad80d4d

but I get tons of other errors.

Anyways, we should concentrate on fixing that issue with the recent SDK / deps :)

**Comment by mdoelker** [comment]
Can you give me the flutter version/channel (flutter doctor output) and the build command you use?

**Comment by amenk** [comment]
I use "flutter build apk"


	Doctor summary (to see all details, run flutter doctor -v):
	[✓] Flutter (Channel unknown, v1.12.13+hotfix.6, on Linux, locale en_US.UTF-8)
	 
	[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
	[✓] Android Studio (version 3.5)
	[!] IntelliJ IDEA Ultimate Edition (version 2016.2)
	    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
	    ✗ Dart plugin not installed; this adds Dart specific functionality.
	    ✗ This install is older than the minimum recommended version of 2017.1.0.
	[!] VS Code (version 1.41.0)
	    ✗ Flutter extension not installed; install from
	      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
	[!] Connected device
	    ! No devices available

	! Doctor found issues in 3 categories.

**Comment by mdoelker** [comment]
Check out the latest commit and follow the AndroidX migration guide for your app https://flutter.dev/docs/development/androidx-migration

**Comment by mdoelker** [comment]
That said, there are some deprecation warnings for some of the plugins used. But I don't expect the functionality to stop working just yet. If you want to be sure, better test that part before release.

**Comment by amenk** [comment]
You mean those?

	Note: Some input files use or override a deprecated API.                
	Note: Recompile with -Xlint:deprecation for details.                    
	Note: /home/self/development/flutter/.pub-cache/hosted/pub.dartlang.org/path_provider-1.5.1/android/src/main/java/io/flutter/plugins/pathprovider/PathProviderPlugin.java uses or overrides a deprecated API.
	Note: Recompile with -Xlint:deprecation for details.                    
	Note: /home/self/development/flutter/.pub-cache/hosted/pub.dartlang.org/share-0.6.3+5/android/src/main/java/io/flutter/plugins/share/SharePlugin.java uses or overrides a deprecated API.
	Note: Recompile with -Xlint:deprecation for details.                    
	/home/self/development/flutter/.pub-cache/hosted/pub.dartlang.org/shared_preferences-0.5.6/android/src/main/java/io/flutter/plugins/sharedpreferences/SharedPreferencesPlugin.java:25: warning: [deprecation] getFlutterEngine() in FlutterPluginBinding has been deprecated
	    setupChannel(binding.getFlutterEngine().getDartExecutor(), binding.getApplicationContext());
		                ^                                               
	1 warning        

shall we try to update those plugins?


Actually I have the problem, that the splash screen does not disappear now, have to yet reproduce this with the example app.

**Comment by amenk** [comment]
I am getting this error directly after running

	E/flutter (14248): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized.
	E/flutter (14248): If you're running an application and need to access the binary messenger before `runApp()` has been called (for example, during plugin initialization), then you need to explicitly call the `WidgetsFlutterBinding.ensureInitialized()` first.
	E/flutter (14248): If you're running a test, you can call the `TestWidgetsFlutterBinding.ensureInitialized()` as the first line in your test's `main()` method to initialize the binding.
	E/flutter (14248): #0      defaultBinaryMessenger.<anonymous closure> (package:flutter/src/services/binary_messenger.dart:76:7)
	E/flutter (14248): #1      defaultBinaryMessenger (package:flutter/src/services/binary_messenger.dart:89:4)
	E/flutter (14248): #2      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:219:15)
	E/flutter (14248): #3      AssetBundle.loadString (package:flutter/src/services/asset_bundle.dart:67:33)
	E/flutter (14248): #4      CachingAssetBundle.loadString.<anonymous closure> (package:flutter/src/services/asset_bundle.dart:162:56)
	E/flutter (14248): #5      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:293:23)
	E/flutter (14248): #6      CachingAssetBundle.loadString (package:flutter/src/services/asset_bundle.dart:162:27)
	E/flutter (14248): #7      GlobalConfiguration.loadFromAsset (package:global_configuration/global_configuration.dart:37:39)
	E/flutter (14248): #8      main (package:yeneguzo_app/main.dart:13:19)
	E/flutter (14248): #9      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:239:25)
	E/flutter (14248): #10     _rootRun (dart:async/zone.dart:1126:13)
	E/flutter (14248): #11     _CustomZone.run (dart:async/zone.dart:1023:19)
	E/flutter (14248): #12     _runZoned (dart:async/zone.dart:1518:10)
	E/flutter (14248): #13     runZoned (dart:async/zone.dart:1502:12)
	E/flutter (14248): #14     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:231:5)
	E/flutter (14248): #15     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:307:19)
	E/flutter (14248): #16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
	E/flutter (14248):

**Comment by amenk** [comment]
Looks like I am missing that line in my main.dart

  WidgetsFlutterBinding.ensureInitialized();

it's already in the example :)

https://stackoverflow.com/questions/57689492/flutter-unhan

**Comment by amenk** [comment]
Works. Thank you. Happy new year :)
