### ISSUE TITLE
Reject by Apple: Cannot click Share Link

### ISSUE THREAD

**Issue by amenk** [trufi-association/trufi-app#357]
We got a reject from Apple for YeneGuzo App 0.6.2, I guess it's also an issue in core?

> Specifically, no action occurred when we tapped on the share button.

[IPad Pro 12.9 2018 at BrowserStack](https://app-live.browserstack.com/dashboard#os=iOS&os_version=13.0&device=iPad+Pro+12.9+2018&zoom_to_fit=true&full_screen=true&speed=1&app_hashed_id=app_store)

Can you provide me with a .ipa file with the latest Trufi Build (with the share app button) so I can test?

Wild guess: If the Ipad does not have a messenger installed, nothing can happen, because there is no way to share the app. So maybe we should show an error message stating that no sharing method was found.

**Comment by amenk** [comment]
If I click on the feedback Icon I also get "Cannot launch"

![image](https://user-images.githubusercontent.com/1087128/71925150-b500c680-3190-11ea-89d9-e8acc7ecde23.png)

**Comment by mdoelker** [comment]
That's weird though. There should be an app that can handle mailto protocol always.

**Comment by amenk** [comment]
I don't thinks so ;-) Will try to fix it.

**Comment by mdoelker** [comment]
Alright, just remembered the mail app is not installed in the Simulator, so that is to be expected ;)

But, as they complained about the share button, that one works for me. What is happening for you when you click share?

This is what it should look like:
![image](https://user-images.githubusercontent.com/2145319/71927346-9224e100-3195-11ea-8c37-ef6034fb3d3f.png)

**Comment by amenk** [comment]
Nothing happens, they tested in a iPad -- I guess not even messages was available :)

**Comment by mdoelker** [comment]
But the Share Sheet is not bound to that app afaik. You pick where you share it to anyway. Could just be copy to clipboard.

**Comment by amenk** [comment]
True, clipboard sharing should be available though

**Comment by mdoelker** [comment]
What is the exception?

**Comment by mdoelker** [comment]
https://github.com/flutter/flutter/issues/47220

**Comment by amenk** [comment]
works in my emulator, thanks

**Comment by mdoelker** [comment]
![image](https://user-images.githubusercontent.com/2145319/71932139-8e965780-319f-11ea-97e8-9615b6f23d5b.png)
